CREATE TABLE employees (
                           id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                           full_name   VARCHAR2(150) NOT NULL,
                           email       VARCHAR2(150) NOT NULL,
                           department  VARCHAR2(100),
                           salary      NUMBER(12,2) NOT NULL,
                           created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                           CONSTRAINT uq_employees_email UNIQUE (email)
);